In [1]:
import numpy as np 

In [2]:
# recap of list comprehension
x= [1,3,5,7]
[10*i for i in x]

[10, 30, 50, 70]

In [3]:
#Same task as above can be done using numpy
nparray=np.array(x)
print(nparray)

[1 3 5 7]


In [4]:
#Mapping
print(nparray*10)

[10 30 50 70]


In [5]:
#filtering
print(nparray[nparray <= 3])

[1 3]


In [9]:
nparray = np.array([-4000, 1, 8, 5])
print(nparray)
print(nparray.dtype)

[-4000     1     8     5]
int32


In [11]:
npX2dnp=np.array([[1, 2, 3], [4, 5, 6]])
print(npX2dnp)

[[1 2 3]
 [4 5 6]]


In [12]:
npX3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7,8,9], [10, 11, 12]]])
print(npX3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
print(npX3d.shape)

(2, 2, 3)


In [14]:
npX3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
npX3d[1] 

array([[ 7,  8,  9],
       [10, 11, 12]])

In [16]:
npX3d[1, 0]

array([7, 8, 9])

In [17]:
npX3d[1][0]

array([7, 8, 9])

In [18]:
npX3d[1][0][1]

8

In [19]:
x = np.array([-2, -4, 7, 10, 12])
print("Sum :", x.sum())
print("Product :", x.prod())
print("Min :", x.min()) 
print("Max :", x.max()) 
print("Max element is at position ", x.argmax())
#Find the max element of the array

Sum : 23
Product : 6720
Min : -4
Max : 12
Max element is at position  4


In [20]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [21]:
#creating an array of zeros
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [32]:
#pass a tuple of 2 elements to the function zeros
np.zeros((5,2))
#what is np.ones(5)
#what is np.ones((2,3) )

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [22]:
#Indexing array
x=[1.6,3.4,4.2]
npx = np.array(x)
print(npx)

[ 1.6  3.4  4.2]


In [23]:
print(npx[-1]) #last element is indexed from -1
print(npx[:2])
print(npx[-2])

4.2
[ 1.6  3.4]
3.4


In [24]:
x=np.array([3.4,5,5.4,5.7,4.1])
print(x)
x<5
print(x[x<5])

[ 3.4  5.   5.4  5.7  4.1]
[ 3.4  4.1]


In [25]:
#Indexing two dimensional arrays
np2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np2d)
print(np2d[1]) #prints the second array
print(np2d[1,1]) #prints the second arrays second elemnt or np2d[1][1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
5


In [26]:
np3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(np3d)
print(np3d[0])
print(np3d[0,1])
print(np3d[0,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[4 5 6]
5


In [27]:
#Array operations
x=np.array([2,4,6,8,10])
print(x.sum())
print(x.prod())
print(x.min())
print(x.max())
print(x.argmax())
# How do you Find the highest element in the array

30
3840
2
10
4


In [28]:
npx = np.array([[1,2,3],[4,5,6]])
print(npx * npx)
print(npx - 2)
print(npx.mean()-npx)

[[ 1  4  9]
 [16 25 36]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2.5  1.5  0.5]
 [-0.5 -1.5 -2.5]]


In [29]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
x.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
x1 = x.reshape((5, 2))
x1.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
x1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
nparr1 = np.array([[1, 2, 3], [4, 5, 6]])
nparr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [34]:
np.concatenate([nparr1,nparr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
np.vstack((nparr1, nparr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
np.concatenate([nparr1,nparr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [35]:
np.hstack([nparr1, nparr2])
print(np.where(x))
print(x)
sorted(x,reverse=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)
[0 1 2 3 4 5 6 7 8 9]


[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [37]:
#split the array after the second row
np.split(np.vstack((nparr1, 
                    nparr2)), 2)
np.sort(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
outcome = np.random.randint(1, 7, size=10)
print(outcome)

[6 6 5 2 5 5 4 5 4 1]


In [38]:
outcome = np.random.randint(1, 7, size=(3, 3))
print(outcome)

[[1 5 6]
 [5 2 2]
 [6 4 6]]


In [12]:
x = [10, 11, 12, 34]
np.random.shuffle(x)
print(x)

[11, 12, 34, 10]
