In [2]:
import tensorflow as tf

In [15]:
state = tf.Variable(0)

In [16]:
one = tf.constant(1)

In [17]:
new_value = tf.add(state,one)

In [18]:
update = tf.assign(state,new_value)

In [6]:
update = tf.assign(one,new_value) ### Error of updating constant

AttributeError: 'Tensor' object has no attribute 'assign'

In [23]:
init_op = tf.initialize_all_variables()

In [24]:
with tf.Session() as session:
        session.run(init_op)
        print(session.run(state))
        for _ in range(3):
            session.run(update)
            print(session.run(state))

0
1
2
3


In [29]:
a = tf.placeholder(tf.float32)

In [30]:
b=a*2

In [33]:
with tf.Session as sess:
    result=sess.run(b,feed_dict={a:3.5})
    print(result)

7.0


In [38]:
dictionary = {a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}
with tf.Session() as sess:
    result = sess.run(b,feed_dict = dictionary)
    print(result)


[[[  2.   4.   6.]
  [  8.  10.  12.]
  [ 14.  16.  18.]
  [ 20.  22.  24.]]

 [[ 26.  28.  30.]
  [ 32.  34.  36.]
  [ 38.  40.  42.]
  [ 44.  46.  48.]]]


In [1]:
a = tf.placeholder(tf.float32)
b = tf.Variable(20)
c = 4*a*a+32*b*b+35
with tf.Session as sess:
    result=sess.run(c,feed_dict={a:4})
    print(result)

NameError: name 'tf' is not defined